In [66]:
import torch
from mpmath import sqrt

In [67]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
t1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [68]:
# sum求和。【掌握】
s_1 = t1.sum()  # 将张量中所有的元素值进行求和
s_2 = t1.sum(dim=0) # 按照第一个维度进行计算
s_3 = t1.sum(dim=1) # 按照第二个维度进行计算
S_4 = t1.sum(dim=-1) # 按照最后一个维度进行计算。常用
# s_5 = t1.sum(dim=2)

print("-" * 40)
print(t1)
print("-" * 40)
print(f"s_1 --> {s_1}")
print(f"s_2 --> {s_2}")
print(f"s_3 --> {s_3}")
print(f"S_4 --> {S_4}")
# print(f"s_5 --> {s_5}")

----------------------------------------
tensor([[1., 2., 3.],
        [4., 5., 6.]])
----------------------------------------
s_1 --> 21.0
s_2 --> tensor([5., 7., 9.])
s_3 --> tensor([ 6., 15.])
S_4 --> tensor([ 6., 15.])


In [69]:
# 其他计算函数
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [70]:
print("-" * 40)
print(t2)
print("-" * 40)
mean_result = t2.mean() # 算均值=21/6
print(f"mean_result = {mean_result}")

min_result = t2.min()
print(f"min_result = {min_result}")

sqrt_result = torch.sqrt(t2)
print(f"sqrt_result = {sqrt_result}")

log2_result = torch.log(t2)
print(f"log2_result = {log2_result}")


----------------------------------------
tensor([[1., 2., 3.],
        [4., 5., 6.]])
----------------------------------------
mean_result = 3.5
min_result = 1.0
sqrt_result = tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
log2_result = tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [71]:
# sum(dim)作用在三维的张量上
torch.manual_seed(129)
t9 = torch.randint(low=1, high=5, size=(2,3,4))
t9

tensor([[[4, 4, 1, 3],
         [1, 3, 3, 1],
         [2, 3, 3, 3]],

        [[2, 2, 2, 2],
         [2, 2, 1, 2],
         [1, 4, 2, 2]]])

In [72]:
print("-->", t9.sum())
print("0-->", t9.sum(dim=0))
print("1-->", t9.sum(dim=1))
print("2-->", t9.sum(dim=2))
print("-1-->", t9.sum(dim=-1))

--> tensor(55)
0--> tensor([[6, 6, 3, 5],
        [3, 5, 4, 3],
        [3, 7, 5, 5]])
1--> tensor([[ 7, 10,  7,  7],
        [ 5,  8,  5,  6]])
2--> tensor([[12,  8, 11],
        [ 8,  7,  9]])
-1--> tensor([[12,  8, 11],
        [ 8,  7,  9]])
