In [53]:
import torch

In [54]:
t1 = torch.randint(low=1, high=10, size=(2, 3))
t2 = torch.randint(low=1, high=10, size=(2, 3))
print("-" * 40)
print(t1)
print(t2)
print("-" * 40)


----------------------------------------
tensor([[3, 1, 4],
        [8, 3, 5]])
tensor([[3, 9, 9],
        [8, 9, 1]])
----------------------------------------


In [55]:
# cat/concat
cat_1 = torch.cat(tensors=[t1, t2], dim=0)
print(cat_1) # 4行3列

tensor([[3, 1, 4],
        [8, 3, 5],
        [3, 9, 9],
        [8, 9, 1]])


In [56]:
cat_2 = torch.cat(tensors=[t1, t2], dim=1)
print(cat_2)

tensor([[3, 1, 4, 3, 9, 9],
        [8, 3, 5, 8, 9, 1]])


In [57]:
# 因为上面创建的是二维张量，因此dim的取值最大是1
# cat_3 = torch.cat(tensors=[t1,t2], dim=2)
# print(cat_3)

In [58]:
# 注意：除了拼接的维度以外，其他维度必须相同
t3 = torch.randint(low=1, high=10, size=(2, 3))
t4 = torch.randint(low=1, high=10, size=(4, 3)) # 列数相同，因此正常
# t4 = torch.randint(low=1, high=10, size=(2, 4))   # 列数不同，因此报错
# t4
print(t3)
print(t4)

cat_4 = torch.cat(tensors=[t3, t4], dim=0)
print(cat_4)

tensor([[4, 4, 9],
        [3, 5, 9]])
tensor([[5, 6, 7],
        [3, 7, 8],
        [4, 5, 2],
        [7, 6, 7]])
tensor([[4, 4, 9],
        [3, 5, 9],
        [5, 6, 7],
        [3, 7, 8],
        [4, 5, 2],
        [7, 6, 7]])


In [59]:
# stack：张量的形状要完全一致
t6 = torch.randint(low=1, high=10, size=(5,6))
t7 = torch.randint(low=1, high=10, size=(5,6))
# t7 = torch.randint(low=1, high=10, size=(5,7))
# t7 = torch.randint(low=1, high=10, size=(7,6))
print(t6)
print(t7)
print(torch.stack(tensors=[t6, t7], dim=0))

tensor([[1, 6, 1, 9, 7, 5],
        [8, 7, 6, 6, 9, 2],
        [2, 9, 3, 7, 8, 9],
        [2, 5, 8, 1, 8, 4],
        [3, 6, 7, 4, 5, 3]])
tensor([[5, 1, 1, 3, 9, 5],
        [1, 7, 4, 1, 4, 9],
        [3, 8, 5, 5, 2, 8],
        [7, 5, 9, 3, 5, 1],
        [4, 3, 3, 8, 5, 8],
        [8, 6, 9, 2, 3, 9],
        [7, 2, 3, 4, 3, 2]])


RuntimeError: stack expects each tensor to be equal size, but got [5, 6] at entry 0 and [7, 6] at entry 1