In [873]:
import torch
import numpy as np

In [874]:
# ----------- 创建张量 -------------
# 1 基础创建torch.tensor
"""
    总结：
    掌握/常用的是 torch.tensor
"""
# 1.1- 标量创建张量
# 查看源代码：ctrl+鼠标左键
t1 = torch.tensor(data=999)
t1

tensor(999)

In [875]:
# 1.2- numpy中的ndarray数组创建张量
arr1 = np.random.randn(2, 3)
arr1


array([[ 0.23348026, -1.74535883, -0.53179199],
       [-2.86531991, -0.46397587, -0.59273421]])

In [876]:
t2 = torch.tensor(data=arr1)
t2

tensor([[ 0.2335, -1.7454, -0.5318],
        [-2.8653, -0.4640, -0.5927]], dtype=torch.float64)

In [877]:
# 1.3- 通过容器创建张量
t3 = torch.tensor([11, 22, 33])
t3

tensor([11, 22, 33])

In [878]:
t4 = torch.tensor([1.99, 2.888, 3.66])
t4

tensor([1.9900, 2.8880, 3.6600])

In [879]:
# 查看张量中元素的数据类型
t4.dtype

torch.float32

In [880]:
# 2 其他创建方式
# 注意：下面的写法是生成包含5个元素的张量。而不是将5变成张量
t5 = torch.Tensor(5)
t5

tensor([-2.7249e+36,  2.0865e-42,  1.4013e-45,  0.0000e+00,  1.4013e-45])

In [881]:
t5 = torch.Tensor([5])
t5

tensor([5.])

In [882]:
t5.dtype

torch.float32

In [883]:
# 3 创建指定类型的张量
t6 = torch.IntTensor([5])
t6

tensor([5], dtype=torch.int32)

In [884]:
t6 = torch.IntTensor([5.9999]) # 只保留整数位
t6

tensor([5], dtype=torch.int32)

In [885]:
t7 = torch.DoubleTensor([5.12])
t7

tensor([5.1200], dtype=torch.float64)

In [886]:
t7 = torch.DoubleTensor([5])
t7

tensor([5.], dtype=torch.float64)

In [887]:
# 4 创建线性张量
# arange生成的范围是[start,end)，左闭右开
# 注意：step表示步长
t8 = torch.arange(start=1, end=10, step=1)
t8

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [888]:
# linspace生成的范围是[start,end]，左右都是闭区间
# 注意：steps不表示步长，表示要生成多少个元素
# t9 = torch.linspace(start=1,end=6,steps=6)
t9 = torch.linspace(start=1, end=10, steps=10)
t9

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [889]:
# 5 随机张量
# 生成区间是[low,high)。左闭右开的区间
t10 = torch.randint(low=1, high=5, size=(4, ))# 生成包含4个元素的向量张量
t10

tensor([4, 1, 2, 3])

In [890]:
t10 = torch.randint(low=1, high=5, size=(2,3, 4 ))
t10

tensor([[[1, 4, 4, 2],
         [2, 1, 2, 3],
         [2, 4, 1, 3]],

        [[2, 4, 4, 4],
         [1, 2, 1, 1],
         [1, 3, 4, 1]]])

In [891]:
# 获得随机数种子
print(torch.initial_seed())

# 手动设置随机数种子
torch.manual_seed(127)
t11 = torch.randint(low=1, high=5,size=(2,3,4))    # 生成三维张量
print(t11)

127
tensor([[[2, 1, 3, 1],
         [1, 4, 2, 4],
         [2, 1, 4, 4]],

        [[4, 2, 2, 4],
         [3, 1, 2, 2],
         [2, 3, 3, 1]]])


In [892]:
t12 = torch.rand(4) # 随机生成指定个数的小数
t12

tensor([0.7313, 0.2974, 0.7635, 0.5420])

In [893]:
t12 = torch.rand(size=(2,3,4))
t12

tensor([[[0.3120, 0.2961, 0.2752, 0.7241],
         [0.7582, 0.7048, 0.1127, 0.6142],
         [0.1111, 0.9318, 0.0182, 0.3809]],

        [[0.1440, 0.2452, 0.6083, 0.8952],
         [0.6465, 0.7892, 0.5625, 0.8666],
         [0.1350, 0.9597, 0.8182, 0.2901]]])

In [894]:
# 随机生成小数：小数满足标准正态分布（均值为0，方差为1）
t13 = torch.randn(4)
t13

tensor([ 0.3022, -0.2511, -0.7932, -0.1066])

In [895]:
# 6 创建指定值的张量
t14 = torch.randn(size=(2,3,4))
t14

tensor([[[-0.4065,  0.2029,  0.4567, -1.2668],
         [ 0.9656,  0.8811, -0.2961,  1.3518],
         [ 0.0277, -0.4225,  0.6665,  2.7128]],

        [[-0.9388,  0.2563, -2.5961, -0.0900],
         [-0.4210, -1.2833,  2.3391,  0.3991],
         [-0.7542,  0.2250,  1.0715, -0.7022]]])

In [896]:
"""
    1- ones创建指定形状的全1张量
    2- ones_like，仿照某个张量的形状，创建指定形状的全1张量
    3- zeros创建指定形状的全0张量。【掌握】
    4- zeros_like，仿照某个张量的形状，创建指定形状的全0张量
    5- full创建指定形状，并且元素值也是人为指定的张量
    6- full_like，仿照某个张量的形状，并且元素值是人为指定的张量
"""
t15 = torch.ones(size=(3,4))
t16 = torch.ones_like(t14)
t17 = torch.zeros(size=(3,4))
t18 = torch.zeros_like(t14)
t19 = torch.full(size=(3,4), fill_value=999)
t20 = torch.full_like(t14, 666)

print(f"ones-->{t15}")
print(f"ones_like-->{t16}")
print(f"zeros-->{t17}")
print(f"full_like-->{t18}")
print(f"full_like-->{t19}")
print(f"full_like-->{t20}")


ones-->tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
ones_like-->tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
zeros-->tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
full_like-->tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
full_like-->tensor([[999, 999, 999, 999],
        [999, 999, 999, 999],
        [999, 999, 999, 999]])
full_like-->tensor([[[666., 666., 666., 666.],
         [666., 666., 666., 666.],
         [666., 666., 666., 666.]],

        [[666., 666., 666., 666.],
         [666., 666., 666., 666.],
         [666., 666., 666., 666.]]])


In [897]:
# 7 张量元素数据类型转换
t_1 = torch.tensor([11, 22, 33])
t_1.dtype

torch.int64

In [898]:
# 通用的写法。掌握
t_2 = t_1.type(dtype=torch.float16) # 推荐的写法
print(t_2)
t_2.dtype

tensor([11., 22., 33.], dtype=torch.float16)


torch.float16

In [899]:
t_2 = t_1.type(dtype=torch.DoubleTensor)
print(t_2)
t_2.dtype

tensor([11., 22., 33.], dtype=torch.float64)


torch.float64

In [900]:
t_3 = torch.tensor([1.678, 2.543])  # 默认是float32])
print(t_3)
t_3.dtype

tensor([1.6780, 2.5430])


torch.float32

In [901]:
t_4 = t_3.half()   # float16
t_4.dtype

torch.float16

In [902]:
t_4 = t_3.short()  # 短整型int16
t_4.dtype

torch.int16

In [903]:
t_4 = t_3.int()  # int32
t_4.dtype

torch.int32

In [904]:
t_4 = t_3.long()   # 长整型int64
t_4.dtype

torch.int64