In [247]:
import torch

In [248]:
# 1--------------- reshape -------------
t0 = torch.tensor([[11, 22, 33], [44, 55, 66]])
t0

tensor([[11, 22, 33],
        [44, 55, 66]])

In [249]:
# 获得张量的形状
print(f"张量形状：{t0.shape}, 行数：{t0.shape[0]}, 列数：{t0.shape[1]}")
print(f"张量形状：{t0.size()}, 行数：{t0.size(0)}, 列数：{t0.size(1)}")

张量形状：torch.Size([2, 3]), 行数：2, 列数：3
张量形状：torch.Size([2, 3]), 行数：2, 列数：3


In [250]:
# reshape修改张量形状：修改前后，元素个数必须完全一致
# 2行3列 -> 1行6列
t1 = t0.reshape(1, 6)
print(t1, t1.shape)

# -1表示内部自动给你进行计算。注意：只能有一个位置设置为-1
# t2 = t0.reshape(1, -1)
t2 = t0.reshape(-1, 1)
# t2 = t0.reshape(-1, -1)   # 不能有多个-1
print(t2, t2.shape)

tensor([[11, 22, 33, 44, 55, 66]]) torch.Size([1, 6])
tensor([[11],
        [22],
        [33],
        [44],
        [55],
        [66]]) torch.Size([6, 1])


In [251]:
# 2--------------- squeeze和unsqueeze -------------
"""
    squeeze：降维。例如：3维变2维
    unsqueeze：升维。例如：2维变3维
    但是，注意：不管是升维还是降维，前后的元素个数必须一致
"""
t3 = torch.randint(low=0, high=5, size=(4, 1, 5))
print(t3.shape, t3)

torch.Size([4, 1, 5]) tensor([[[4, 2, 4, 3, 1]],

        [[2, 0, 0, 3, 4]],

        [[2, 4, 3, 4, 2]],

        [[1, 3, 1, 0, 1]]])


In [252]:
t4 = t3.squeeze()
print(t4, t4.shape)

# t5 = t3.squeeze(dim=0) # [4,1,5]
# t5 = t3.squeeze(dim=1) # [4,5]
t5 = t3.squeeze(dim=2) # [4,1, 5]
print(t5, t5.shape)

tensor([[4, 2, 4, 3, 1],
        [2, 0, 0, 3, 4],
        [2, 4, 3, 4, 2],
        [1, 3, 1, 0, 1]]) torch.Size([4, 5])
tensor([[[4, 2, 4, 3, 1]],

        [[2, 0, 0, 3, 4]],

        [[2, 4, 3, 4, 2]],

        [[1, 3, 1, 0, 1]]]) torch.Size([4, 1, 5])


In [253]:
t6 = torch.randint(low=0, high=5, size=(4, 5))
print(t6, t6.shape)

tensor([[4, 1, 4, 4, 2],
        [4, 0, 2, 2, 0],
        [1, 4, 2, 2, 0],
        [4, 0, 0, 4, 1]]) torch.Size([4, 5])


In [254]:
# t7 = t6.unsqueeze(dim=0) # [1, 4, 5]
# t7 = t6.unsqueeze(dim=1) # [1, 4, 5]
t7 = t6.unsqueeze(dim=2) # [4, 5, 1]
# t7 = t6.unsqueeze(dim=3)
print(t7, t7.shape)

tensor([[[4],
         [1],
         [4],
         [4],
         [2]],

        [[4],
         [0],
         [2],
         [2],
         [0]],

        [[1],
         [4],
         [2],
         [2],
         [0]],

        [[4],
         [0],
         [0],
         [4],
         [1]]]) torch.Size([4, 5, 1])


In [255]:
# 3--------------- transpose和permute -------------
"""
    1- transpose和permute都是用来交换张量的维度
    2- transpose同一时刻，只能交换两个位置，不能交换多个
    3- permute同一时刻，能交换多个

    注意：交换前后的元素个数必须一致
"""
t8 = torch.randint(low=0, high=5, size=(4, 5, 3))
print(t8, t8.shape)

tensor([[[0, 3, 4],
         [1, 3, 2],
         [1, 1, 2],
         [0, 1, 1],
         [1, 0, 4]],

        [[0, 1, 1],
         [4, 3, 2],
         [2, 0, 3],
         [0, 2, 1],
         [2, 1, 1]],

        [[0, 1, 1],
         [4, 1, 1],
         [4, 3, 4],
         [3, 3, 3],
         [3, 4, 4]],

        [[1, 2, 1],
         [2, 3, 1],
         [0, 2, 1],
         [0, 2, 3],
         [4, 2, 3]]]) torch.Size([4, 5, 3])


In [256]:
# 需求1：[4,5,3] -> [3,5,4]
# dim0和dim1的参数值没有顺序要求
t9 = t8.transpose(dim0=0,dim1=2)
print(t9, t9.shape)


tensor([[[0, 0, 0, 1],
         [1, 4, 4, 2],
         [1, 2, 4, 0],
         [0, 0, 3, 0],
         [1, 2, 3, 4]],

        [[3, 1, 1, 2],
         [3, 3, 1, 3],
         [1, 0, 3, 2],
         [1, 2, 3, 2],
         [0, 1, 4, 2]],

        [[4, 1, 1, 1],
         [2, 2, 1, 1],
         [2, 3, 4, 1],
         [1, 1, 3, 3],
         [4, 1, 4, 3]]]) torch.Size([3, 5, 4])


In [257]:
t9 = t8.transpose(dim0=2,dim1=0)
print(t9, t9.shape)

tensor([[[0, 0, 0, 1],
         [1, 4, 4, 2],
         [1, 2, 4, 0],
         [0, 0, 3, 0],
         [1, 2, 3, 4]],

        [[3, 1, 1, 2],
         [3, 3, 1, 3],
         [1, 0, 3, 2],
         [1, 2, 3, 2],
         [0, 1, 4, 2]],

        [[4, 1, 1, 1],
         [2, 2, 1, 1],
         [2, 3, 4, 1],
         [1, 1, 3, 3],
         [4, 1, 4, 3]]]) torch.Size([3, 5, 4])


In [258]:
# 需求2：[4,5,3] -> [3,4,5]
# 需求拆解：[4,5,3] -> [3,5,4] -> [3,4,5]
t10 = t8.transpose(dim0=0,dim1=2)
print(t10, t10.shape)

t11 = t10.transpose(dim0=1,dim1=2)
print(t11, t11.shape)

tensor([[[0, 0, 0, 1],
         [1, 4, 4, 2],
         [1, 2, 4, 0],
         [0, 0, 3, 0],
         [1, 2, 3, 4]],

        [[3, 1, 1, 2],
         [3, 3, 1, 3],
         [1, 0, 3, 2],
         [1, 2, 3, 2],
         [0, 1, 4, 2]],

        [[4, 1, 1, 1],
         [2, 2, 1, 1],
         [2, 3, 4, 1],
         [1, 1, 3, 3],
         [4, 1, 4, 3]]]) torch.Size([3, 5, 4])
tensor([[[0, 1, 1, 0, 1],
         [0, 4, 2, 0, 2],
         [0, 4, 4, 3, 3],
         [1, 2, 0, 0, 4]],

        [[3, 3, 1, 1, 0],
         [1, 3, 0, 2, 1],
         [1, 1, 3, 3, 4],
         [2, 3, 2, 2, 2]],

        [[4, 2, 2, 1, 4],
         [1, 2, 3, 1, 1],
         [1, 1, 4, 3, 4],
         [1, 1, 1, 3, 3]]]) torch.Size([3, 4, 5])


In [259]:
# 需求：[4,5,3] -> [3,4,5]
# dim的变化[0,1,2] -> [2,0,1]
t12 = t8.permute(dims=[2, 0, 1])
print(t12, t12.shape)

tensor([[[0, 1, 1, 0, 1],
         [0, 4, 2, 0, 2],
         [0, 4, 4, 3, 3],
         [1, 2, 0, 0, 4]],

        [[3, 3, 1, 1, 0],
         [1, 3, 0, 2, 1],
         [1, 1, 3, 3, 4],
         [2, 3, 2, 2, 2]],

        [[4, 2, 2, 1, 4],
         [1, 2, 3, 1, 1],
         [1, 1, 4, 3, 4],
         [1, 1, 1, 3, 3]]]) torch.Size([3, 4, 5])
