In [375]:
import  torch

In [376]:
torch.manual_seed(129)
t0 = torch.randint(low=0, high=10, size=(4, 5))
t0

tensor([[7, 1, 2, 6, 6],
        [0, 2, 0, 7, 4],
        [4, 0, 9, 3, 1],
        [9, 3, 1, 0, 7]])

In [377]:
# 【掌握】1----- 简单的行、列索引 --------
# 语法：张量对象[行索引,列索引]
# 获取第一行
print(t0[0])

# 获取第一列
print(t0[:, 0])

t0[2, 4] #3

tensor([7, 1, 2, 6, 6])
tensor([7, 0, 4, 9])


tensor(1)

In [378]:
# 【掌握】2------ 范围索引：与容器中的切片操作完全一样 -------
# 语法：张量对象[行索引开始:行索引结束:步长, 列索引开始:列索引结束:步长]，左闭右开
# 需求1：前3行的前2列数据
t0[:3, :2]

tensor([[7, 1],
        [0, 2],
        [4, 0]])

In [379]:
# 需求2：第2行到最后的行，并且前2列的数据
t0[1:, :2]

tensor([[0, 2],
        [4, 0],
        [9, 3]])

In [380]:
# 【了解】3------- 列表索引 -----
# 需求1：返回(第0行,第1列)、(1,2)两个位置的元素
print(t0)
t0[[0, 1], [1, 2]]

tensor([[7, 1, 2, 6, 6],
        [0, 2, 0, 7, 4],
        [4, 0, 9, 3, 1],
        [9, 3, 1, 0, 7]])


tensor([1, 0])

In [381]:
# 需求2：获取两个元素的坐标是(2,4)、(3,3) 左闭右开
# 语法：张量对象[[行1,行2], [列1,列2]]
print(t0)
t0[[2, 3], [4, 3]]

tensor([[7, 1, 2, 6, 6],
        [0, 2, 0, 7, 4],
        [4, 0, 9, 3, 1],
        [9, 3, 1, 0, 7]])


tensor([1, 0])

In [382]:
# 获取4个元素，坐标分别是(2,4)、(2,3)、(3,4)、(3,3)
print(t0)
print(t0[[[2], [3]], [4, 3]])

tensor([[7, 1, 2, 6, 6],
        [0, 2, 0, 7, 4],
        [4, 0, 9, 3, 1],
        [9, 3, 1, 0, 7]])
tensor([[1, 3],
        [7, 0]])


In [383]:
# 【了解】4------- 布尔索引 -------
# 需求1：第3列大于5的，对应的行数据
# 取出第3列
print(t0)
print(t0[:, 3])

# 判断是否是大于5
print(t0[:, 3] > 5)

# 取出对应的行数据
print(t0[t0[:, 3] > 5, :])


print(t0[:, 3][t0[:, 3] > 5])   # 输出 tensor([6, 7])

tensor([[7, 1, 2, 6, 6],
        [0, 2, 0, 7, 4],
        [4, 0, 9, 3, 1],
        [9, 3, 1, 0, 7]])
tensor([6, 7, 3, 0])
tensor([ True,  True, False, False])
tensor([[7, 1, 2, 6, 6],
        [0, 2, 0, 7, 4]])
tensor([6, 7])


In [384]:
# 【了解】5------ 多维索引 --------
t1 = torch.randint(0,10,size=(3,4,5))
t1



# 获取2轴上的数据


tensor([[[8, 9, 9, 7, 3],
         [4, 2, 4, 5, 1],
         [1, 7, 3, 4, 2],
         [2, 6, 1, 6, 0]],

        [[0, 8, 4, 8, 8],
         [4, 5, 0, 8, 7],
         [2, 1, 2, 2, 5],
         [1, 7, 1, 2, 0]],

        [[6, 0, 8, 8, 7],
         [4, 3, 4, 7, 3],
         [7, 8, 7, 4, 3],
         [6, 0, 1, 5, 0]]])

In [385]:
# 获取0轴上的数据
t1[0, :, :]

tensor([[8, 9, 9, 7, 3],
        [4, 2, 4, 5, 1],
        [1, 7, 3, 4, 2],
        [2, 6, 1, 6, 0]])

In [386]:
# 获取1轴上的数据
t1[:, 0, :]

tensor([[8, 9, 9, 7, 3],
        [0, 8, 4, 8, 8],
        [6, 0, 8, 8, 7]])

In [387]:
# 获取2轴上的数据
t1[:, :, 0]

tensor([[8, 4, 1, 2],
        [0, 4, 2, 1],
        [6, 4, 7, 6]])