In [12]:
import torch
import numpy as np

In [13]:
# 1------------------ 张量转成Numpy ------------------
t1 = torch.tensor([11, 22, 33])
print(t1)

# 默认共享内存
arr1 = t1.numpy()
print(type(arr1))
print(arr1)

# 使用copy，不共享内存。就是一个深拷贝
arr1 = t1.numpy().copy()

t1[1] = 999
print(f"张量：{t1}")
print(f"Numpy：{arr1}")


tensor([11, 22, 33])
<class 'numpy.ndarray'>
[11 22 33]
张量：tensor([ 11, 999,  33])
Numpy：[11 22 33]


In [14]:
# 2------------------ Numpy转成张量 ------------------
arr2 = np.array([11, 22, 33])
print(type(arr2))
print(arr2)

<class 'numpy.ndarray'>
[11 22 33]


In [15]:
# from_numpy会共享内存
t2 = torch.from_numpy(arr2)
print(t2)

arr2[1] = 999
print(f"Numpy: {arr2}")
print(f"张量：{t2}")
print("-" * 50)

# torch.tensor(Numpy)不会共享内存
arr3 = np.array([11, 22, 33])
t3 = torch.tensor(arr2)
print(type(t3))
print(t3)

arr2[1] = 666
print(f"Numpy：{arr2}")
print(f"张量：{t3}")


tensor([11, 22, 33])
Numpy: [ 11 999  33]
张量：tensor([ 11, 999,  33])
--------------------------------------------------
<class 'torch.Tensor'>
tensor([ 11, 999,  33])
Numpy：[ 11 666  33]
张量：tensor([ 11, 999,  33])
